import { Shield, AlertTriangle, CheckCircle2, Activity } from "lucide-react";
import Scoreboard from "../components/coverage/Scoreboard";
import AlertQueueTable from "../components/alerts/AlertQueueTable";
import AlertDetailsPanel from "../components/alerts/AlertDetailsPanel";
import AIAssistantPanel from "../components/assistant/AIAssistantPanel";
import MetricsPanel from "../components/blue/MetricsPanel";
import PageShell from "../components/layout/PageShell";
import PageHeader from "../components/layout/PageHeader";
import EmptyState from "../components/ui/EmptyState";
import IncidentInvestigationBoardV2 from "../components/blue/IncidentInvestigationBoardV2";
import PanelCard from "../components/ui/PanelCard";
import PanelHeader from "../components/ui/PanelHeader";

/* ========================================
   🔵 Blue View
======================================== */

export default function BlueView({
    metrics,
    activeAlerts,
    selectedAlert,
    setSelectedAlert,
    updateAlertTriageStatus,
    visibleStatus,
    coverage,
    activeControls,
    mode,
    selectedScenario,
}) {
    const headerStats = [
        {
            label: "Alerts",
            value: activeAlerts.length,
            icon: <AlertTriangle className="h-4 w-4 text-cyber-amber" />,
        },
        {
            label: "Coverage",
            value: `${metrics?.coverage ?? 0}%`,
            icon: <Shield className="h-4 w-4 text-cyber-violet" />,
        },
        {
            label: "Logs",
            value: metrics?.totalLogs ?? 0,
            icon: <Activity className="h-4 w-4 text-cyber-blue" />,
        },
        {
            label: "Momentum",
            value: `${metrics?.momentum ?? 0}%`,
            icon: <CheckCircle2 className="h-4 w-4 text-cyber-green" />,
        },
    ];

    return (
        <PageShell
            header={
                <PageHeader
                    eyebrow="BLUE OPERATIONS"
                    title="Alert Triage & Analyst Workflow"
                    description="Review triggered detections, triage alerts, inspect details and validate the analyst-facing defensive workflow."
                    stats={headerStats}
                />
            }
            left={
                <>
                    {/* ========================================
             🔴🔵 Scoreboard
          ======================================== */}
                    <Scoreboard metrics={metrics} />
                    {/* ========================================
             📊 MTTD / MTTR
          ======================================== */}
                    <MetricsPanel metrics={metrics} visibleStatus={visibleStatus} />

                    {/* ========================================
             🧠 Analyst Summary
          ======================================== */}
                    <PanelCard variant="defense">
                        <PanelHeader
                            icon={<Shield className="h-5 w-5 text-cyber-violet" />}
                            title="Blue Team Operations"
                            subtitle="Triage, review and track active detections"
                        />

                        <div className="mt-4">
                            <PanelCard variant="signal" dense>
                                <p className="mb-2 text-xs uppercase tracking-[0.18em] text-cyber-muted">
                                    Queue Summary
                                </p>
                                <p className="text-sm leading-7 text-cyber-text">
                                    The blue team workspace centralizes analyst-facing alerts generated by the simulation
                                    engine. Use this area to inspect detections, update triage status, and validate how
                                    defensive controls affect the queue.
                                </p>
                            </PanelCard>
                        </div>
                    </PanelCard>
                </>
            }
            center={
                <>
                    {/* ========================================
             🚨 Alert Queue
          ======================================== */}
                    <AlertQueueTable
                        alerts={activeAlerts}
                        selectedAlertId={selectedAlert?.id}
                        onSelectAlert={setSelectedAlert}
                        onUpdateAlertStatus={updateAlertTriageStatus}
                    />

                    <IncidentInvestigationBoardV2
                        alert={selectedAlert}
                        selectedScenario={selectedScenario}
                        activeControls={activeControls}
                        visibleStatus={visibleStatus}
                        coverage={coverage}
                    />
                </>
            }
            right={
                <>

                    {/* ========================================
             🔍 Alert Details
          ======================================== */}
                    <AlertDetailsPanel alert={selectedAlert}
                    />

                    {/* ========================================
             🤖 AI Assistant
          ======================================== */}
                    <AIAssistantPanel
                        selectedAlert={selectedAlert}
                        visibleStatus={visibleStatus}
                        coverage={coverage}
                        activeControls={activeControls}
                        mode={mode}
                        selectedScenario={selectedScenario}
                    />
                </>
            }
        />
    );
}

/* ========================================
   🧩 UI Helpers
======================================== */

function SectionTitle({ icon, title, subtitle }) {
    return (
        <div>
            <div className="flex items-center gap-2">
                {icon}
                <h2 className="text-lg font-semibold">{title}</h2>
            </div>
            <p className="mt-1 text-sm text-cyber-muted">{subtitle}</p>
        </div>
    );
}