import { useEffect, useMemo, useRef, useState } from "react";
import Sidebar from "./components/Sidebar";
import Alerts from "./pages/Alerts";
import Dashboard from "./pages/Dashboard";
import AttackMap from "./pages/AttackMap";
import CTF from "./pages/CTF";
import Logs from "./pages/Logs";
import Investigations from "./pages/Investigations";

import AttackStory from "./pages/AttackStory";

import { getIncidentParams } from "./lib/incidentParams";
import LinkedIncidentBanner from "./components/LinkedIncidentBanner";
import { linkedIncidentAlerts } from "./data/linkedIncidents";
import { getEcosystemIncidentById } from "@/data/ecosystem/incidents";

import { Badge } from "@/components/ui/Badge";
import { CyberPanel } from "@/components/ui/CyberPanel";
import { HeaderCard } from "@/components/ui/HeaderCard";
import { Activity, Play, Square, RotateCcw, Radio, ShieldAlert, Siren, FolderOpen, Clock3, ShieldCheck } from "lucide-react";
import { HeaderMetric } from "@/components/ui/HeaderMetric";
import { AICopilotPanel } from "@/components/ui/AICopilotPanel";

export default function App() {
  const [page, setPage] = useState("alerts");
  const [alertsGlobal, setAlertsGlobal] = useState([]);
  const [demoMode, setDemoMode] = useState(false);
  const [demoStep, setDemoStep] = useState("idle");
  const [demoTrigger, setDemoTrigger] = useState(0);
  const demoTimeouts = useRef([]);
  const [resetTrigger, setResetTrigger] = useState(0);
  const [tickerIndex, setTickerIndex] = useState(0);
  const [currentTime, setCurrentTime] = useState(new Date());

  const [linkedIncident] = useState(() => getIncidentParams());

  const incidentParams = getIncidentParams();

  const incident = getEcosystemIncidentById(
    incidentParams.incidentId || "incident-001"
  );

  const alerts = linkedIncidentAlerts[incident.id] || [];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const now = currentTime;

  function clearDemoTimeouts() {
    demoTimeouts.current.forEach((timeoutId) => clearTimeout(timeoutId));
    demoTimeouts.current = [];
  }

  function startRecruiterDemo() {
    clearDemoTimeouts();

    setDemoMode(true);
    setDemoTrigger(Date.now());
    setPage("alerts");
    setDemoStep("Attack simulation started");

    const t1 = setTimeout(() => {
      setDemoStep("Live alerts are being generated");
    }, 2000);

    const t2 = setTimeout(() => {
      setPage("dashboard");
      setDemoStep("Dashboard overview of the incident");
    }, 6000);

    const t3 = setTimeout(() => {
      setPage("attackmap");
      setDemoStep("Global attack visualization");
    }, 10000);

    const t4 = setTimeout(() => {
      setPage("investigations");
      setDemoStep("Correlated investigation workflow");
    }, 14000);

    const t5 = setTimeout(() => {
      setPage("ctf");
      setDemoStep("Interactive SOC investigation challenge");
    }, 18000);

    demoTimeouts.current = [t1, t2, t3, t4, t5];
  }

  function stopRecruiterDemo() {
    clearDemoTimeouts();
    setDemoMode(false);
    setDemoStep("Demo stopped");
  }

  function resetRecruiterDemo() {
    clearDemoTimeouts();
    setDemoMode(false);
    setDemoStep("idle");
    setPage("alerts");
    setDemoTrigger(0);
    setAlertsGlobal([]);
    setResetTrigger(Date.now());
  }

  function getNarrationText() {
    if (!demoMode) return "";

    switch (page) {
      case "alerts":
        return "This view shows live security alerts generated by the SOC simulator. Analysts can triage incidents, inspect severity, and respond to suspicious activity.";
      case "dashboard":
        return "The dashboard provides a real-time overview of attack volume, severity distribution, and SOC monitoring metrics.";
      case "attackmap":
        return "The attack map visualizes hostile activity targeting the environment, helping analysts understand the global threat picture.";
      case "logs":
        return "This log stream simulates SIEM ingestion and allows analysts to inspect raw events for suspicious patterns and indicators.";
      case "investigations":
        return "The investigation view correlates events by IP to reconstruct the attack path and support incident response decisions.";
      case "ctf":
        return "The CTF lab turns simulated incidents into hands-on investigations, allowing users to practice real SOC analysis skills.";
      default:
        return "SOC simulation in progress.";
    }
  }

  const fallbackTickerMessages = [
    "Monitoring pipelines active",
    "Alert telemetry streaming",
    "Investigation workflows operational",
    "SOC command center online",
    "Threat visibility enabled",
  ];

  const dynamicTickerMessages =
    alertsGlobal.length > 0
      ? alertsGlobal.slice(0, 5).map(
        (alert) =>
          `[${alert.time}] ${alert.name} · ${alert.ip} · ${alert.severity.toUpperCase()}`
      )
      : fallbackTickerMessages;

  useEffect(() => {
    if (!linkedIncident.incidentId) return;

    if (linkedIncident.technique || linkedIncident.user || linkedIncident.ip) {
      setPage("alerts");
    }
  }, [linkedIncident]);

  const linkedAlertsForContext = useMemo(() => {
    const baseAlerts = linkedIncidentAlerts[linkedIncident.incidentId] ?? [];

    if (linkedIncident.phishResult !== "confirmed") {
      return baseAlerts;
    }

    const phishingAlert = {
      id: "soc-incident-001-phish-confirmed",
      name: "Confirmed Phishing Campaign",
      severity: "critical",
      status: "open",
      ip: linkedIncident.ip || "185.77.44.21",
      user: linkedIncident.user || "j.smith",
      technique: "T1566",
      tag: "Initial Access",
      source: "PhishScope",
      time: new Date().toLocaleTimeString(),
      description:
        "PhishScope confirmed credential-harvesting activity tied to secure-login-support.com.",
      logs: [
        "PhishScope confirmed phishing",
        "Credential harvesting detected",
        `Domain: ${linkedIncident.domain || "secure-login-support.com"}`,
        `Affected user: ${linkedIncident.user || "j.smith"}`,
        "MITRE T1566 Phishing",
      ],
    };

    return [
      phishingAlert,
      ...baseAlerts.filter((alert) => alert.id !== phishingAlert.id),
    ];
  }, [linkedIncident]);

  const criticalAlerts = alertsGlobal.filter((a) => a.severity === "critical").length;
  const openIncidents = alertsGlobal.filter((a) => a.status === "open").length;

  const avgRisk = alertsGlobal.length
    ? Math.round(
      alertsGlobal.reduce((sum, alert) => {
        const scoreMap = {
          low: 25,
          medium: 50,
          high: 75,
          critical: 100,
        };

        return sum + (scoreMap[alert.severity] || 0);
      }, 0) / alertsGlobal.length
    )
    : 0;

  const formattedTime = now.toLocaleTimeString("fr-FR", {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });

  const formattedDate = now.toLocaleDateString("fr-FR", {
    weekday: "short",
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  const activeAlerts = alertsGlobal.length;

  const pipelineHealth =
    alertsGlobal.some((alert) => alert.severity === "critical")
      ? "Degraded"
      : "Healthy";

  const ingestionRate = demoMode
    ? Math.max(12, alertsGlobal.length * 3)
    : alertsGlobal.length > 0
      ? Math.max(3, alertsGlobal.length)
      : 0;

  const heartbeat = demoMode || alertsGlobal.length > 0;

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-[radial-gradient(circle_at_top_left,rgba(37,99,235,0.18),transparent_32%),radial-gradient(circle_at_85%_10%,rgba(14,165,233,0.10),transparent_28%),linear-gradient(135deg,#020617,#07111f_45%,#020617)] text-slate-100">
      <div className="flex min-h-screen">
        <Sidebar setPage={setPage} currentPage={page} />

        <main className="flex-1 overflow-hidden">
          <div className="min-h-screen space-y-6 p-6">

            <CyberPanel className="px-4 py-3">
              <div className="flex items-center gap-3 overflow-hidden">
                <div className="flex items-center gap-2 whitespace-nowrap text-blue-300">
                  <Radio className="h-4 w-4" />
                  <span className="text-xs font-bold uppercase tracking-[0.22em]">
                    Live Feed
                  </span>
                </div>

                <div className="h-4 w-px bg-blue-400/20" />

                <p className="truncate text-sm font-medium tracking-wide text-slate-200">
                  {dynamicTickerMessages[tickerIndex]}
                </p>
              </div>
            </CyberPanel>

            <LinkedIncidentBanner incident={linkedIncident} />

            <HeaderCard
              eyebrow="CyberOps Ecosystem"
              title="SOC Command Center"
              description="Monitor alerts, investigate incidents, follow attack paths and simulate real SOC response workflows."
            >
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
                <HeaderMetric
                  icon={Clock3}
                  label="Local Time"
                  value={formattedTime}
                  description={formattedDate}
                  tone="blue"
                  pulse
                  glow
                />

                <HeaderMetric
                  icon={Activity}
                  label="Pipeline Health"
                  value={pipelineHealth}
                  description="Event processing online"
                  tone={pipelineHealth === "Healthy" ? "green" : "yellow"}
                />

                <HeaderMetric
                  icon={Radio}
                  label="Live Telemetry"
                  value={`${ingestionRate} EPS`}
                  description="Simulated events per second"
                  tone="cyan"
                  pulse={heartbeat}
                />

                <HeaderMetric
                  icon={ShieldCheck}
                  label="Active Alerts"
                  value={activeAlerts}
                  description={demoMode ? "Recruiter demo active" : "Standard monitoring"}
                  tone={demoMode ? "blue" : "slate"}
                />
              </div>
            </HeaderCard>

            <CyberPanel>
              <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-400">
                    Recruiter Demo Control
                  </p>

                  {(demoMode || demoStep !== "idle") ? (
                    <p className="mt-2 text-sm text-slate-300">
                      🎬 Demo Mode:{" "}
                      <span className="font-semibold text-blue-300">{demoStep}</span>
                    </p>
                  ) : (
                    <p className="mt-2 text-sm text-slate-400">
                      Launch a guided incident walkthrough across the SOC interface.
                    </p>
                  )}
                </div>

                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={startRecruiterDemo}
                    className="inline-flex items-center gap-2 rounded-xl border border-blue-500/30 bg-blue-500/15 px-4 py-2 text-sm font-semibold text-blue-200 transition hover:bg-blue-500/25"
                  >
                    <Play className="h-4 w-4" />
                    Start Demo
                  </button>

                  <button
                    onClick={stopRecruiterDemo}
                    className="inline-flex items-center gap-2 rounded-xl border border-orange-500/30 bg-orange-500/15 px-4 py-2 text-sm font-semibold text-orange-200 transition hover:bg-orange-500/25"
                  >
                    <Square className="h-4 w-4" />
                    Stop
                  </button>

                  <button
                    onClick={resetRecruiterDemo}
                    className="inline-flex items-center gap-2 rounded-xl border border-slate-500/30 bg-slate-500/10 px-4 py-2 text-sm font-semibold text-slate-200 transition hover:bg-slate-500/20"
                  >
                    <RotateCcw className="h-4 w-4" />
                    Reset
                  </button>
                </div>
              </div>

              {demoMode && (
                <div className="mt-4 rounded-2xl border border-cyan-500/25 bg-cyan-500/10 p-4">
                  <div className="mb-2 flex items-center gap-2 text-cyan-300">
                    <Activity className="h-4 w-4" />
                    <p className="text-xs font-bold uppercase tracking-[0.22em]">
                      Recruiter Briefing
                    </p>
                  </div>

                  <p className="text-sm leading-relaxed text-slate-100">
                    {getNarrationText()}
                  </p>
                </div>
              )}
            </CyberPanel>
            <div className="grid grid-cols-1 gap-6 2xl:grid-cols-[1fr_360px]">
              <div className="min-w-0">
                {page === "alerts" && (
                  <Alerts
                    setGlobalAlerts={setAlertsGlobal}
                    demoTrigger={demoTrigger}
                    resetTrigger={resetTrigger}
                    linkedAlerts={linkedAlertsForContext}
                  />
                )}

                {page === "attackstory" && <AttackStory alerts={alertsGlobal} />}
                {page === "dashboard" && <Dashboard alerts={alertsGlobal} />}
                {page === "attackmap" && <AttackMap alerts={alertsGlobal} />}
                {page === "logs" && <Logs alerts={alertsGlobal} />}
                {page === "investigations" && <Investigations alerts={alertsGlobal} />}
                {page === "ctf" && <CTF alerts={alertsGlobal} />}
              </div>
              {/* RIGHT = AI */}
              <AICopilotPanel alerts={alertsGlobal} page={page} />
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}